src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Cocur\Slugify\Slugify;
use DateTimeImmutable;
use DateTimeZone;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
#[UniqueEntity('title')]    // unique for title field
class Property
{

    const HEAT = [
        1 => 'Electrique',
        2 => 'Gaz'
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\NotNull]
    #[Assert\Length(min: 5, max: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\NotNull]
    #[Assert\Length(min: 3)]
    private ?string $description = null;

    #[ORM\Column]
    #[Assert\NotNull]
    #[Assert\Range(
        min: 10,
        max: 200,
        notInRangeMessage: 'La surface doit être situé entre {{ min }}m² et {{ max }}m².',
    )]
    private ?int $surface = null;

    #[ORM\Column]
    #[Assert\NotNull]
    private ?int $rooms = null;

    #[ORM\Column]
    #[Assert\NotNull]
    private ?int $bedrooms = null;

    #[ORM\Column]
    #[Assert\NotNull]
    private ?int $floor = null;

    #[ORM\Column]
    #[Assert\NotNull]
    private ?int $price = null;

    #[ORM\Column]
    #[Assert\NotNull]
    #[Assert\Choice([1, 2])]
    private ?int $heat = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull]
    #[Assert\Regex('/^[0-9]{5}$/')]
    private ?string $postal_code = null;

    #[ORM\Column(options: ["default" => false])]
    private ?bool $sold = false;

    #[ORM\Column]
    #[Assert\NotNull]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToMany(targetEntity: Option::class, inversedBy: 'properties')]
    private Collection $options;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    private ?Picture $picture = null;

    #[ORM\OneToMany(mappedBy: 'property', targetEntity: Picture::class, orphanRemoval: true, cascade: ['persist'])]
    private Collection $pictures;

    // All : constraints for each element of pictureFiles array
    #[Assert\All([
        new Assert\Image(
            mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
            mimeTypesMessage: 'Format de fichier invalide ({{ type }}). Format(s) accepté(s) : {{ types }}'
        )
    ])]
    private $pictureFiles;

    // scale: number of decimals, precision: number total of digits (ex: 34.5205)
    #[ORM\Column(scale: 4, precision: 6)]
    private ?float $latitude = null;

    #[ORM\Column(scale: 4, precision: 7)]
    private ?float $longitude = null;

    public function __construct()
    {
        // Date = at the creation of instance
        $this->created_at = new DateTimeImmutable('now', new DateTimeZone('Europe/Paris'));
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    // Slug = formatted title using for Url
    public function getSlug(): ?string
    {
        $slugify = (new Slugify());
        return $slugify->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }


    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeatType(): ?string
    {
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function isSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Option>
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options->add($option);
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }


    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    /**
     * @return ?Picture
     */
    public function getFirstPicture(): ?Picture
    {
        return $this->picture;
    }

    /**
     * @return ?Picture
     */
    public function setPicture(Picture $picture): self
    {
        $this->picture = $picture;
        return $this;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures->add($picture);
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * Get the value of pictureFiles
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * Set the value of pictureFiles
     */
    public function setPictureFiles($pictureFiles): self
    {
        // For each picture file
        foreach ($pictureFiles as $file) {
            $picture = new Picture();
            $picture->setImageFile($file);
            $this->addPicture($picture);
        }

        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', null, ['label' => 'Titre', 'attr' => ['title' => 'Titre du bien', 'class' => 'border border-primary']])  // this is a way to translate
            ->add('description')
            ->add('surface', null, ['attr' => [
                'min' => 0,
                'placeholder' => 60
            ]])
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price', null, ['attr' => [
                'min' => 0,
                'placeholder' => 100000
            ]])
            ->add('heat', ChoiceType::class, ['choices' => $this->getChoices()]) // display heat name instead of int
            ->add('options', EntityType::class, [
                'required' => false,
                'class' => Option::class,       // Option from Entity, not Form
                'choice_label' => 'name',       // option name as input label
                'expanded' => true,             // change selecte input to checkbox
                'multiple' => true,              // multitple choice available
                'attr' => [
                    'class' => 'd-flex justify-content-evenly'
                ]
            ])
            ->add('pictureFiles', FileType::class, [
                'label' => 'Importer des images',
                'required' => false,
                'multiple' => true
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('latitude', HiddenType::class)    // hide the input, because not need in the form
            ->add('longitude', HiddenType::class)
            ->add('sold', null, [
                'label' => 'Vendu (cochez la case si le bien a été vendu)',
            ])
            // ->add('save', SubmitType::class, [   // Not need because the form includes submit button
            //     'label' => 'Enregistrer'
            // ])
            // ->add('created_at')  Not need for the form
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    // Get heat name instead of int
    private function getChoices()
    {
        $choices = Property::HEAT;
        $result = [];
        foreach ($choices as $key => $value) {
            $result[$value] = $key;
        }
        return $result;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Picture;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Knp\Component\Pager\PaginatorInterface;     // for paginate the list of properties

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    // Shows all unsold properties (12 per page)
    #[Route('/biens', name: 'property.index')]
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        // Search filter
        $search = new PropertySearch;
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        // response
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $this->repository->paginateAllVisible($search, $request->query->getInt('page', 1)),
            'form' => $form->createView()
        ]);
    }



    // Shows one property
    // using regex for slug in param
    /**
     * @param Property $property
     * @param string $slug
     * @return Response
     */
    #[Route('/biens/{id}-{slug}', name: 'property.show', requirements: ["slug" => "[a-z0-9\-]*"])]
    public function show(string $slug, Property $property, Request $request, ContactNotification $notification): Response
    {
        // if slug is different, so redirect with 301
        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute(
                'property.show',
                [
                    'id' => $property->getId(),
                    'slug' => $property->getSlug()
                ],
                301
            );
        }

        // create contact form for the current property
        $contact = new Contact;
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        // if contact form is submitted and valid
        if ($form->isSubmitted() && $form->isValid()) {

            // Send mail
            $notification->notify($contact);
            $this->addFlash('success', 'Votre message a bien été envoyé. Nous vous contacterons dès que possible.');
            // return $this->redirectToRoute(
            //     'property.show',
            //     [
            //         'id' => $property->getId(),
            //         'slug' => $property->getSlug()
            //     ]
            // );
        }

        $pictures = $this->em->getRepository(Picture::class)->findForProperty($property);
        // dd($pictures);

        // check if the property has an image
        if ($pictures->containsKey($property->getId())) {
            $property->setPicture($pictures->get($property->getId()));
        }

        // not need find method here because link between id in param and Property
        // $property = $this->repository->find($id);
        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties',
            'contactForm' => $form->createView()
        ]);
    }
    // Voir les annotations S6
}

templates/property/_property.html.twig
{# save this template in cache, set an unique key to identify the cache and an expiration time(optional) #}

{# cache "property" ~ property.id ~ ";" ~ property.updatedAt #}
<div class="col-4 mb-3">
    <div class="card h-100" style="border: 2px solid rgb(175, 210, 211);">
        {# check if the property has at least one image #}
        <a href="{{ path('property.show', {slug: property.slug, id: property.id }) }}">
            {% if property.firstPicture %}
            <img src="{{ vich_uploader_asset(property.firstPicture, 'imageFile') | imagine_filter('property_thumb') }}"
                class="card-img-top" alt="Photo du bien" width="100%" height="auto">
            {% else %}
            <img src="{{ '/images/properties/no-image.png' | imagine_filter('property_thumb') }}" class="card-img-top"
                alt="no-image.png" width="100%" height="auto">
            {% endif %}
        </a>
        <div class="card-body py-2" style="background-color:rgb(225, 240, 240);">
            <h5 class="card-title">
                <a href="{{ path('property.show', {slug: property.slug, id: property.id }) }}" class="text-dark">{{
                    property.title
                    }}</a>
            </h5>
            <p class="card-text m-0">
                {{property.surface}} m² - {{ property.rooms }} pièce{% if property.rooms > 1 %}s{% endif %}
            </p>
            <p class="card-text m-0">
                {{ property.city }} ({{ property.postalCode}})
            </p>
            <p class="fs-4 m-0">{{ property.formattedPrice }} €</p>
            <!-- <p class="text-secondary pt-4">
                {% for option in property.options %}
                <span class="p-1 border border-secondary rounded" style="background-color:rgb(235, 246, 246);">
                    {{ option.name }}
                </span>
                {% endfor %}
            </p> -->
        </div>
    </div>
</div>
{# endcache #}

templates/property/index.html.twig
{# property index page : This page shows all unsold properties (front office) #}

{% extends 'base.html.twig' %}

{% block title %}Nos biens - Immo78{% endblock %}

{% block body %}

<div class="container" style="max-width: 1020px;">
    <div class="row">
        <div class="mt-5">
            {{ form_start(form) }}
            <div class="form row">
                <div class="col-3">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col-3">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col justify-content-center">
                    {{ form_row(form.options) }}
                </div>
            </div>
            <div class="form row">
                <div class="col-6">
                    {{ form_row(form.address, {id: 'search_address'}) }}
                    <!-- <div class="form-group">
                        <input type="text" value="" placeholder="Adresse" id="search_address" class="form-control">
                    </div> -->
                </div>
                <div class="col-3">
                    {{ form_row(form.distance) }}
                </div>
                <div class="col">
                    <button class="btn btn-success">Rechercher</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
        <div class="my-2">
            Résultat de la recherche : {{ properties.getTotalItemCount }} bien(s) trouvé(s)
        </div>
        {% for property in properties %}
        {{ include('property/_property.html.twig') }}
        {% endfor %}
        {# display navigation #}
        <div class="pagination d-flex justify-content-center">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>
</div>

{% endblock %}

templates/property/show.html.twig
{# property show page : This page shows one property #}

{% extends 'base.html.twig' %}

{% block title %}{{ property.title }} - Immo78{% endblock %}

{% block body %}

<div class="container mt-4" style="max-width: 1020px;">
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
    {% if not contactForm.vars.valid %}
    <div class="alert alert-danger">Veuillez remplir correctement le formulaire.</div>
    {% endif %}
    <div class="row">

        <!-- IMAGE BLOCK -->
        <div class="col-md-7">
            {# check if the property has at least one image #}
            {% if property.firstPicture %}
            {# display caroussel to show all images#}
            <div id="carouselExample" class="carousel slide border border-secondary">
                <div class="carousel-inner">
                    {% for picture in property.pictures %}
                    <div class="carousel-item {% if picture == property.firstPicture %}active{% endif %}">
                        <a href="{{ vich_uploader_asset(picture, 'imageFile') }}">
                            <img src="{{ vich_uploader_asset(picture, 'imageFile') | imagine_filter('property_medium') }}"
                                alt="Photo du bien" style="max-width: 100%;">
                        </a>
                    </div>
                    {% endfor %}
                </div>
                {% if property.pictures.count > 1 %}
                <button class="carousel-control-prev bg-secondary" type="button" data-bs-target="#carouselExample"
                    data-bs-slide="prev" style="width: fit-content;">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next bg-secondary" type="button" data-bs-target="#carouselExample"
                    data-bs-slide="next" style="width: fit-content;">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
                {% endif %}
            </div>

            {% else %}
            <img src="{{ '/images/properties/no-image.png' | imagine_filter('property_medium') }}" class="card-img-top"
                alt="...">
            {% endif %}
        </div>

        <!-- INFORMATION BLOCK -->
        <div class="col-md-5">
            <h3 id="property-title">{{ property.title }}</h3>
            <h4>{{ property.rooms }} pièces - {{ property.surface }} m²</h4>
            <h4 class="fw-bold">{{ property.formattedPrice }} €</h4>
            <p>
                <span class="text-decoration-underline">Description</span> : <span class="fst-italic">{{
                    property.description | nl2br }}</span>
            </p>
            <a href="#" class="btn btn-secondary rounded-0" id="contactButton" {% if contactForm.vars.submitted %}
                style="display: none;" {% endif %}>Contacter l'agence</a>

            <div id="contactForm" {% if not contactForm.vars.submitted %}style="display: none;" {% endif %}>
                <div class="p-3 bg-secondary" style='position: absolute;z-index: 1;'>
                    {{ form_start(contactForm) }}
                    <div class="row text-light">
                        <div class="col">{{ form_row(contactForm.lastName) }}</div>
                        <div class="col">{{ form_row(contactForm.firstName) }}</div>
                    </div>
                    <div class="row text-light">
                        <div class="col">{{ form_row(contactForm.phone) }}</div>
                        <div class="col">{{ form_row(contactForm.email) }}</div>
                    </div>
                    <div class="col text-light">{{ form_rest(contactForm) }}</div>
                    <div class="form-group">
                        <button class="btn btn-light rounded-0">Envoyer</button>
                        <button class="btn btn-danger rounded-0" id="cancelButton">Annuler</button>
                    </div>
                    {{ form_end(contactForm) }}
                </div>
            </div>
        </div>
    </div>

    <hr class="my-4">

    <div class="row">

        <!-- FEATURES BLOCK -->
        <div class="col-md-6">
            <h3>Caractéristiques du bien</h3>
            <table class="table table-success table-bordered opacity-75">
                <tr>
                    <td>Surface habitable en m²</td>
                    <td>{{ property.surface }}</td>
                </tr>
                <tr>
                    <td>Pièces</td>
                    <td>{{ property.rooms }}</td>
                </tr>
                <tr>
                    <td>Chambres</td>
                    <td>{{ property.bedrooms }}</td>
                </tr>
                <tr>
                    <td>Etages</td>
                    <td>{{ property.floor }}</td>
                </tr>
                <tr>
                    <td>Type de chauffage</td>
                    <td>{{ property.heatType }}</td>
                </tr>
            </table>
        </div>

        <!-- OPTIONS BLOCK -->
        <div class="col-md-6">
            <h3>Équipement(s)</h3>
            <table class="table table-success table-bordered opacity-75">
                {% if (property.options.count > 0) %}
                {% for option in property.options %}
                <tr>
                    <td>{{ option.name }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td>Aucun équipement n'est lié à ce bien</td>
                </tr>
                {% endif %}
            </table>
        </div>
    </div>

    <hr class="my-4">

    <div>
        <h3>Localisation du bien</h3>
        <p>{{property.address}} - {{property.postalCode}} {{property.city}}</p>
    </div>
    <!-- MAP BLOCK -->
    <div id="map" style="width: 100%; height: 600px;" data-lat="{{ property.latitude }}"
        data-lng="{{ property.longitude }}" class="mb-4"></div>

</div>
{% endblock %}